# Generated by Django 4.0.3 on 2022-05-25 14:42

from django.db import migrations, models
import galleryfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comment_post_alter_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='my_images')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=galleryfield.fields.GalleryField(blank=True, null=True, target_model='posts.MyImage'),
        ),
    ]
