# Generated by Django 4.0.4 on 2022-05-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_delete_myimage_remove_post_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('MD', 'Moderation'), ('AR', 'Archive'), ('OK', 'Publicated')], default='MD', max_length=2),
        ),
    ]
